# Generated by Django 5.0.14 on 2026-07-10 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('color_hex', models.CharField(default='#1f7a7d', help_text='ट्याग देखाउँदा प्रयोग हुने रङ (जस्तै: #e8772e)।', max_length=7)),
            ],
            options={
                'verbose_name': 'ट्याग',
                'verbose_name_plural': 'ट्यागहरू',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(help_text='छोटो विवरण — कार्ड/लिस्टमा देखाउनका लागि।', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('software', 'सफ्टवेयर'), ('mobile_app', 'मोबाइल एप'), ('web_portal', 'वेब पोर्टल'), ('game', 'गेम')], db_index=True, default='web_portal', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'योजनामा'), ('in_progress', 'विकासमा'), ('testing', 'परीक्षणमा'), ('active', 'सक्रिय'), ('archived', 'अभिलेखमा')], db_index=True, default='planned', max_length=20)),
                ('icon_emoji', models.CharField(blank=True, help_text='कार्डमा देखाउने इमोजी/आइकन, जस्तै 🚜', max_length=10)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='projects.tag')),
            ],
            options={
                'verbose_name': 'परियोजना',
                'verbose_name_plural': 'परियोजनाहरू',
                'ordering': ['-is_featured', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'योजनामा'), ('in_progress', 'विकासमा'), ('testing', 'परीक्षणमा'), ('completed', 'सफल समापन')], db_index=True, default='planned', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'माइलस्टोन',
                'verbose_name_plural': 'माइलस्टोनहरू',
                'ordering': ['project', 'order', 'due_date'],
                'indexes': [models.Index(fields=['project', 'status'], name='projects_mi_project_dc545b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'project_type'], name='projects_pr_status_b41d0a_idx'),
        ),
    ]
