# Generated by Django 5.0.14 on 2026-07-21 06:21

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_status_b41d0a_idx',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='download_url',
            field=models.URLField(blank=True, help_text='Testing/Active परियोजनाका लागि डाउनलोड लिङ्क।'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'न्यून'), ('medium', 'मध्यम'), ('high', 'उच्च'), ('critical', 'अत्यावश्यक')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='परियोजनाको प्रगति प्रतिशतमा (0-100)।', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='release_date',
            field=models.DateField(blank=True, help_text='वास्तविक रिलिज मिति वा लक्षित मिति (ETA)।', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='release_notes',
            field=models.TextField(blank=True, help_text='रिलिज/परिवर्तन नोटहरू (changelog)।'),
        ),
        migrations.AddField(
            model_name='project',
            name='release_version',
            field=models.CharField(blank=True, help_text='जस्तै: v1.2.0', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot_url',
            field=models.URLField(blank=True, help_text='परियोजनाको स्क्रिनसट/छवि URL (वैकल्पिक)।'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'category'], name='projects_pr_status_7c8b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'priority'], name='projects_pr_status_d9e5a3_idx'),
        ),
    ]
