# Generated by Django 5.0.14 on 2026-07-22 05:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_redesign_project_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=models.TextField(blank=True, help_text='यो परियोजना के हो भन्ने छोटो परिचय अनुच्छेद यहाँ लेख्नुहोस्।', verbose_name='परिचय (Introduction)'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text='हरेक विशेषता छुट्टै लाइनमा लेख्नुहोस् — एक लाइनमा एउटा मात्र विशेषता।', verbose_name='मुख्य विशेषताहरू (Key Features)'),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True, help_text='यो परियोजना किन बनाइयो, यसको मुख्य लक्ष्य के हो भनेर लेख्नुहोस्।', verbose_name='उद्देश्य (Objective)'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_audience',
            field=models.CharField(blank=True, help_text="यो परियोजना कसका लागि हो, जस्तै: 'किसान र कृषि व्यवसायीहरू'।", max_length=250, verbose_name='लक्षित प्रयोगकर्ता समूह (Target Audience)'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='यो माइलस्टोन वास्तवमा कहिले पूरा भयो — पूरा भइसकेपछि मात्र भर्नुहोस्।', null=True, verbose_name='पूरा भएको मिति/समय'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, help_text='यो माइलस्टोनमा के हुन्छ भन्ने छोटो व्याख्या (वैकल्पिक)।', verbose_name='विवरण'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(blank=True, help_text='यो माइलस्टोन कहिलेसम्म पूरा गर्ने लक्ष्य हो (वैकल्पिक)।', null=True, verbose_name='लक्षित मिति'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='सानो अङ्क भएको माइलस्टोन पहिले देखिन्छ (जस्तै: 0, 1, 2...)।', verbose_name='देखिने क्रम'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='परियोजना'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('planned', 'योजनामा'), ('in_progress', 'विकासमा'), ('testing', 'परीक्षणमा'), ('completed', 'सफल समापन')], db_index=True, default='planned', help_text='यो माइलस्टोन हाल कुन अवस्थामा छ भनेर छान्नुहोस्।', max_length=20, verbose_name='अवस्था'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(help_text="माइलस्टोनको छोटो नाम लेख्नुहोस्, जस्तै: 'Beta रिलिज'।", max_length=200, verbose_name='माइलस्टोनको नाम'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('software', 'सफ्टवेयर'), ('mobile_app', 'मोबाइल एप'), ('web_portal', 'वेब पोर्टल'), ('game', 'गेम')], db_index=True, default='web_portal', help_text='यो परियोजना कुन प्रकारको हो — सफ्टवेयर, मोबाइल एप, वेब पोर्टल, वा गेम।', max_length=20, verbose_name='श्रेणी (Category)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='बनेको मिति'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='यो पुरानो/साधारण विवरण फिल्ड हो। नयाँ परियोजनाका लागि तल दिइएका छुट्टाछुट्टै फिल्डहरू (परिचय, उद्देश्य, मुख्य विशेषता, लक्षित समूह) भर्नु सिफारिस गरिन्छ; यो फिल्ड खाली राख्दा पनि हुन्छ।', verbose_name='विवरण (साधारण/पुरानो)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='download_url',
            field=models.URLField(blank=True, help_text="Testing वा Active भएपछि यही लिङ्क प्रयोग हुन्छ — श्रेणी 'वेब पोर्टल' भए 'लाइभ साइट हेर्नुहोस्' र अरू (सफ्टवेयर/मोबाइल एप/गेम) भए 'डाउनलोड गर्नुहोस्' बटन स्वतः देखिन्छ।", verbose_name='डाउनलोड / लाइभ साइट लिङ्क'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon_emoji',
            field=models.CharField(blank=True, help_text='कार्डमा देखाउने इमोजी/आइकन, जस्तै 🚜', max_length=10, verbose_name='इमोजी/आइकन'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='✓ गरे यो परियोजना गृहपृष्ठ र Projects पेजको माथिल्लो भागमा देखिनेछ।', verbose_name='Featured (गृहपृष्ठमा देखाउने?)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='यो परियोजना व्यवस्थापन गर्ने प्रयोगकर्ता (वैकल्पिक — खाली राख्न मिल्छ)।', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='जिम्मेवार प्रयोगकर्ता (Owner)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'न्यून'), ('medium', 'मध्यम'), ('high', 'उच्च'), ('critical', 'अत्यावश्यक')], db_index=True, default='medium', help_text='यो परियोजनालाई हामीले कति प्राथमिकतामा राखेका छौं भन्ने तह छान्नुहोस्।', max_length=20, verbose_name='प्राथमिकता (Priority)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='परियोजनाको प्रगति प्रतिशतमा (0 देखि 100 सम्म कुनै अङ्क)।', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='प्रगति (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(blank=True, help_text='वास्तविक रिलिज मिति वा लक्षित मिति (ETA)।', null=True, verbose_name='रिलिज/लक्षित मिति'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_notes',
            field=models.TextField(blank=True, help_text='रिलिज/परिवर्तन नोटहरू (changelog)।', verbose_name='रिलिज नोटहरू (Changelog)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_version',
            field=models.CharField(blank=True, help_text='जस्तै: v1.2.0', max_length=30, verbose_name='रिलिज संस्करण (Version)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_url',
            field=models.URLField(blank=True, help_text='परियोजनाको स्क्रिनसट वा कभर छवि देखाउने URL (वैकल्पिक)।', verbose_name='स्क्रिनसट/छवि URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='वेब ठेगानामा देखिने छोटो कोड। खाली नै छाड्नुहोस् — नामबाट स्वतः बन्नेछ।', max_length=220, unique=True, verbose_name='URL स्लग'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'योजनामा'), ('in_progress', 'विकासमा'), ('testing', 'परीक्षणमा'), ('active', 'सक्रिय'), ('archived', 'अभिलेखमा')], db_index=True, default='planned', help_text='परियोजना योजनामा, विकासमा, परीक्षणमा, सक्रिय, वा अभिलेखमा — कुन चरणमा छ छान्नुहोस्।', max_length=20, verbose_name='हालको अवस्था (Status)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(help_text='छोटो विवरण — कार्ड/लिस्टमा देखाउनका लागि (१-२ वाक्य)।', max_length=300, verbose_name='छोटो सारांश'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='सान्दर्भिक ट्याग(हरू) छान्नुहोस् (जस्तै: कृषि-टेक)। एकभन्दा बढी छान्न सकिन्छ।', related_name='projects', to='projects.tag', verbose_name='ट्यागहरू (Tags)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text="परियोजनाको पूरा नाम यहाँ लेख्नुहोस्, जस्तै: 'ASW - A Separate World'।", max_length=200, verbose_name='परियोजनाको नाम'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='अपडेट भएको मिति'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color_hex',
            field=models.CharField(default='#1f7a7d', help_text='ट्याग देखाउँदा प्रयोग हुने रङ (जस्तै: #e8772e)।', max_length=7, verbose_name='रङ (Hex कोड)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text="छोटो, स्पष्ट नाम लेख्नुहोस्, जस्तै: 'कृषि-टेक'।", max_length=80, unique=True, verbose_name='ट्यागको नाम'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='खाली नै छाड्नुहोस् — नामबाट स्वतः बन्नेछ।', max_length=90, unique=True, verbose_name='URL स्लग'),
        ),
    ]
