# Generated by Django 5.0.14 on 2026-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_structured_description_and_accessibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='target_audience',
            field=models.TextField(blank=True, help_text="यो परियोजना कसका लागि हो, जस्तै: 'किसान र कृषि व्यवसायीहरू'।", verbose_name='लक्षित प्रयोगकर्ता समूह (Target Audience)'),
        ),
    ]
