# Generated by Django 5.0.14 on 2026-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('summary', models.CharField(help_text='कार्डमा देखिने छोटो विवरण।', max_length=250)),
                ('description', models.TextField(blank=True, help_text='विस्तृत विवरण (भविष्यमा detail page का लागि)।')),
                ('icon_emoji', models.CharField(blank=True, help_text='कार्डमा देखाउने इमोजी, जस्तै 🖥️', max_length=10)),
                ('price_note', models.CharField(blank=True, help_text="जस्तै: 'निःशुल्क परामर्श' वा 'मूल्यको लागि सम्पर्क गर्नुहोस्'।", max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='अनचेक गरे यो सेवा वेबसाइटमा देखिँदैन।')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='सानो नम्बर पहिले देखिन्छ।')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'सेवा',
                'verbose_name_plural': 'सेवाहरू',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='services_se_is_acti_dbc8d8_idx')],
            },
        ),
    ]
