# Generated by Django 5.0.14 on 2026-07-10 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'समाचार सदस्यता',
                'verbose_name_plural': 'समाचार सदस्यताहरू',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('special', 'विशेष समाचार'), ('milestone', 'सफ्टवेयर माइलस्टोन'), ('community', 'समुदाय अपडेटहरू')], db_index=True, max_length=20)),
                ('version_label', models.CharField(blank=True, help_text='सफ्टवेयर संस्करण ट्याग, जस्तै: v1.2.0 (माइलस्टोन समाचारका लागि)।', max_length=30)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='projects.project')),
            ],
            options={
                'verbose_name': 'समाचार',
                'verbose_name_plural': 'समाचारहरू',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('title_snapshot', models.CharField(max_length=250)),
                ('body_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='newsfeed.newspost')),
            ],
            options={
                'verbose_name': 'समाचार रिभिजन',
                'verbose_name_plural': 'समाचार रिभिजनहरू',
                'ordering': ['news_post', '-revision_number'],
            },
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['category', 'is_published', 'published_at'], name='newsfeed_ne_categor_51cad5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsrevision',
            unique_together={('news_post', 'revision_number')},
        ),
    ]
