# Generated by Django 5.0.14 on 2026-07-10 08:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'प्रशासक'), ('editor', 'सम्पादक'), ('contributor', 'योगदानकर्ता'), ('viewer', 'दर्शक')], db_index=True, default='viewer', help_text='प्रयोगकर्ताको प्रणाली-व्यापी भूमिका (system-wide role)।', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='फोन नम्बर मान्य ढाँचामा हुनुपर्छ, जस्तै: +9779812345678', regex='^\\+?977?\\d{7,10}$')])),
                ('is_two_factor_enabled', models.BooleanField(default=False, help_text='दुई-चरण प्रमाणीकरण (2FA) सक्रिय छ/छैन।')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'प्रयोगकर्ता',
                'verbose_name_plural': 'प्रयोगकर्ताहरू',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('project', 'परियोजना'), ('news', 'समाचार'), ('roadmap', 'रोडम्याप'), ('user', 'प्रयोगकर्ता')], db_index=True, max_length=20)),
                ('resource_id', models.PositiveIntegerField(blank=True, help_text='खाली छोड्नुहोस् यदि यो अनुमति यस resource_type का सबै वस्तुमा लागू हुन्छ भने।', null=True)),
                ('permission_level', models.CharField(choices=[('view', 'हेर्न मात्र'), ('edit', 'सम्पादन'), ('manage', 'व्यवस्थापन'), ('owner', 'स्वामी')], default='view', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_acl_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ACL प्रविष्टि',
                'verbose_name_plural': 'ACL प्रविष्टिहरू',
            },
        ),
        migrations.CreateModel(
            name='AuthEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'सफल लगइन'), ('login_failed', 'असफल लगइन प्रयास'), ('logout', 'लगआउट'), ('password_reset', 'पासवर्ड रिसेट'), ('two_factor_verified', '2FA प्रमाणित')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'अथेन्टिकेशन घटना लग',
                'verbose_name_plural': 'अथेन्टिकेशन घटना लगहरू',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, help_text='जिल्ला (जस्तै: भक्तपुर, काठमाडौं)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'प्रोफाइल',
                'verbose_name_plural': 'प्रोफाइलहरू',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='accesscontrolentry',
            index=models.Index(fields=['resource_type', 'resource_id'], name='accounts_ac_resourc_653cc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accesscontrolentry',
            unique_together={('user', 'resource_type', 'resource_id', 'permission_level')},
        ),
        migrations.AddIndex(
            model_name='autheventlog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_3c7df8_idx'),
        ),
    ]
