# Generated by Django 5.0.14 on 2026-07-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="जस्तै: 'वेब डेभलपर' वा साँचो नाम।", max_length=120)),
                ('role', models.CharField(help_text='जस्तै: फ्रन्टइन्ड तथा पहुँचयोग्यता।', max_length=150)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('initials', models.CharField(blank=True, help_text="Avatar circle मा देखिने छोटो अक्षर, जस्तै 'वे'।", max_length=4)),
                ('avatar_url', models.URLField(blank=True, help_text='फोटो राख्न चाहनुभए URL (वैकल्पिक)।')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='सानो नम्बर पहिले देखिन्छ।')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'टोली सदस्य',
                'verbose_name_plural': 'टोली सदस्यहरू',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='team_teamme_is_acti_2b6e1b_idx')],
            },
        ),
    ]
