# Generated by Django 5.0.14 on 2026-07-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='व्यक्तिगत वेबसाइट/पोर्टफोलियो लिङ्क (वैकल्पिक)।'),
        ),
    ]
