# Generated by Django 5.0.14 on 2026-07-10 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'योजनामा'), ('progress', 'विकासमा'), ('testing', 'परीक्षणमा'), ('active', 'सक्रिय')], db_index=True, default='planned', max_length=20)),
                ('target_release_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='ठाडो रोडम्याप-स्पाइनमा देखिने क्रम (सानो नम्बर माथि देखिन्छ)।')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_items', to='projects.tag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_items', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'रोडम्याप वस्तु',
                'verbose_name_plural': 'रोडम्याप वस्तुहरू',
                'ordering': ['order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='जस्तै: v1.2.0', max_length=30, unique=True)),
                ('release_date', models.DateField()),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap_items', models.ManyToManyField(blank=True, related_name='releases', to='roadmaps.roadmapitem')),
            ],
            options={
                'verbose_name': 'रिलिज ट्र्याकर',
                'verbose_name_plural': 'रिलिज ट्र्याकरहरू',
                'ordering': ['-release_date'],
            },
        ),
        migrations.AddIndex(
            model_name='roadmapitem',
            index=models.Index(fields=['status', 'order'], name='roadmaps_ro_status_5f135b_idx'),
        ),
    ]
